batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202405072002
train_epochs: 1000
train_workers: 20
vocab: r.iV-9Mh7&d'XLJqT,)W8cZ"ywUaFGxQso/f:0lpDC6?ztK1gSPmu(beA4+;OE5*jvN!Ink#YRB32H
width: 128
